---
- hosts: all # The hosts directive that defines the targets for that play.
  vars: # The vars section of the playbook defines a list of variables that will be injected in the scope of that play.
    - var1: variable # Standard variable
    - var2: /also/a/variable # Filesystem Path Varaible
    - var3: "{{ ansible_hostname }}" # Fact Cache Variable
  tasks: # A task is the smallest unit of action you can automate using an Ansible playbook.
    - name: Task 1 - print variables # The name property defines the output that will be printed when that task is about to be executed.
      debug: # (The debug module) Modules offer shortcuts to execute operations that you would otherwise have to run as raw bash commands.
        msg: "I am a {{ var1 }}, I am {{ var2 }} on {{ var3 }}" # Modules set of options and properties.
