---
- hosts: all
    vars:
      - pubkey= # pubkey for super user
  become: true
  become_user: "super-user"
  tasks:
  - name: make dir
    file:
      path: "/home/<super-user>/.ssh"
      state: directory
  - name: create empty file
    file:
      path: "/home/<super-user>/.ssh/authorized_keys"
      state: touch
  - name: put pubkey
    lineinfile:
      path: "/home/<super-user>/.ssh/authorized_keys"
      line: "{{ pubkey }}"

# ansible-playbook deploy_authorized_keys.yml --extra-vars='pubkey="<pubkey-for-super-user>”’
