---
- hosts: all
  tasks:
  - name: Add User and Password (Note: use "mkpasswd --method=sha-512" to hash password)
    become: true
    become_user: root
    ansible.builtin.user:
      name: username
      state: present
      password: password
